services:
  linux:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  react:
    build:
      context: .
      dockerfile: Dockerfile_React
    restart: "always"
    ports:
      - "3000:3000"